name: "Simulate Docker Build"

on:
  pull_request:
  schedule:
    - cron: '0 2 * * *' # run daily

jobs:
  docker-build:
    name: "Simulate Docker Build"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.5"

      - name: "Docker Build"
        run: "docker build ."
